### ISSUE TITLE
Producer improvements

### ISSUE THREAD

**Issue by alternativshik** [wikibusiness/aioamqp_consumer#11]
There is no way to use Producer with exchanges and routing keys.

**Comment by hellysmile** [comment]
Hey @alternativshik ! We are on early stage of polishing of this library.
Thank You for the great feedback!

Have You tried to use https://github.com/wikibusiness/aioamqp_consumer/blob/master/aioamqp_consumer/producer.py#L71 ?

as well `queue_name` is might be used as `routing_key` as far as I understand

**Comment by alternativshik** [comment]
Yes, but we should have a way to declare an exchanges and bind they to queues directly from Producer, I think.

I've made some improvements for exchanges, looks like this works good on my production
 
https://github.com/alternativshik/aioamqp_consumer/blob/exchanges/aioamqp_consumer/mixins.py
https://github.com/alternativshik/aioamqp_consumer/blob/exchanges/aioamqp_consumer/producer.py

**Comment by hellysmile** [comment]
Pull request is more then welcome!

**Comment by alternativshik** [comment]
Ok! Сделаем! PR #12

**Comment by alternativshik** [comment]
#12

**Comment by hellysmile** [comment]
Merged, 0.2.0 is on a way

**Comment by hellysmile** [comment]
Release 0.2.0 is on PyPi thanks for contributing! But I've decided to remove features like producer.queue_unbind/queue_delete/exchange_delete cuz it if becomes very complex to manage due in-memory cache of binded\knows queue exchanges... Maybe we need to remove at all this in-memory cache and introduce these features, but it for the next releases
