### ISSUE TITLE
Routing key issues

### ISSUE THREAD

**Issue by hellysmile** [wikibusiness/aioamqp_consumer#15]
Merging https://github.com/wikibusiness/aioamqp_consumer/pull/12 brings that any queue is binded to default routing key `''`, it means each message come all possible queues.

Here is my hotfix https://github.com/wikibusiness/aioamqp_consumer/commit/0b23d5358a70f6f4f411b9fa105428ee98cfd2f3 , but I am not sure is right or not

@alternativshik can You take a look on it?

**Comment by hellysmile** [comment]
Here is my proposal to fix it https://github.com/wikibusiness/aioamqp_consumer/pull/16

But I am NOT sure regarding default rabbitmq routing settings

**Comment by alternativshik** [comment]
@hellysmile hi! Looks good.

**Comment by hellysmile** [comment]
Thanks
